### ISSUE TITLE
Rufo crashes on nested empty hash literal

### ISSUE THREAD

**Issue by lparry** [ruby-formatter/rufo#152]
I've got a test case here: https://github.com/lparry/rufo/commit/9c4e59c9c9c6ffad835f1be572845ad4b362764b

the following causes rufo to explode:

```ruby
{ 1 => {} }
```

output:

```
Failures:

  1) Rufo::Formatter formatter_source_specs/hash_literal.rb.spec formats unnamed test (line: 138)
     Failure/Error: case node.first

     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./lib/rufo/formatter.rb:3840:in `node_line'
     # ./lib/rufo/formatter.rb:3842:in `node_line'
     # ./lib/rufo/formatter.rb:3851:in `node_line'
     # ./lib/rufo/formatter.rb:3855:in `node_line'
     # ./lib/rufo/formatter.rb:3842:in `node_line'
     # ./lib/rufo/formatter.rb:3832:in `need_space_for_hash?'
     # ./lib/rufo/formatter.rb:2305:in `visit_hash'
     # ./lib/rufo/formatter.rb:420:in `visit'
     # ./lib/rufo/formatter.rb:522:in `block (2 levels) in visit_exps'
     # ./lib/rufo/formatter.rb:3658:in `push_node'
     # ./lib/rufo/formatter.rb:521:in `block in visit_exps'
     # ./lib/rufo/formatter.rb:502:in `each'
     # ./lib/rufo/formatter.rb:502:in `each_with_index'
     # ./lib/rufo/formatter.rb:502:in `visit_exps'
     # ./lib/rufo/formatter.rb:198:in `visit'
     # ./lib/rufo/formatter.rb:176:in `format'
     # ./lib/rufo/formatter.rb:14:in `format'
     # ./spec/lib/rufo/formatter_spec.rb:43:in `block (3 levels) in assert_source_specs'
```
